version: '3'

services:
  ### PHP-FPM ##############################################
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/usr/src/api
    expose:
      - "9000"

  ### NGINX Server #########################################
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/usr/src/api
      - ${DATA_PATH}/nginx:/var/log/nginx
    ports:
      - "${NGINX_HTTP_PORT}:80"
    depends_on:
      - php

  ### MySQL ################################################
  mysql:
    build:
      context: ./docker/mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${APP_TIMEZONE}
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

  ### phpMyAdmin ###########################################
  phpmyadmin:
    build: ./docker/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - mysql

  ### Redis ################################################
  redis:
    build: ./docker/redis
    volumes:
      - ${DATA_PATH}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"

  ### Admin UI build ################################################
  admin:
    build: ./admin
    env_file:
      - ./admin/.env
    volumes:
      - ./admin:/usr/src/admin:rw,cached
      - /usr/src/admin/node_modules
    ports:
      - "8080:8080"
