version: '3'

services:
  ### PHP-FPM ##############################################
  php:
    build:
      context: ./
    volumes:
      - ./:/usr/src/api
    expose:
      - "9000"

  ### NGINX Server #########################################
  nginx:
    build:
      context: ./docker/nginx
      args:
        - APP_ENV=${APP_ENV}
    volumes:
      - ./:/usr/src/api
      - ${DATA_PATH}/nginx:/var/log/nginx
    ports:
      - "${NGINX_HTTP_PORT}:80"
    depends_on:
      - php
      - admin

  ### MySQL ################################################
  mysql:
    build:
      context: ./docker/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${APP_TIMEZONE}
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql

  ### phpMyAdmin ###########################################
  phpmyadmin:
    build:
      context: ./docker/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=pma
      - MYSQL_PASSWORD=pmapass
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - mysql

  ### Redis ################################################
  redis:
    build:
      context: ./docker/redis
    volumes:
      - ${DATA_PATH}/redis:/data

  ### Admin UI build ################################################
  admin:
    build:
      context: ./admin
    volumes:
      - ./admin:/usr/src/admin
