api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: Bookstore API Platform's demo
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        jsonhal: ['application/hal+json']
        jsonapi: ['application/vnd.api+json']
        json: ['application/json']
        html: ['text/html']
    patch_formats:
        json: ['application/merge-patch+json']
        jsonapi: ['application/vnd.api+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
